### ISSUE TITLE
Not possible to add http://spk.synologyitalia.com/

### ISSUE THREAD

**Issue by c-schmitz** [jdel/sspks#57]
When I try to add it as package source my DS215+ says it is invalid.

**Comment by jdel** [comment]
Hello,

Unfortunately, I am not supporting the deployment of sspks done by synologyitalia.

They are using the legacy version, which has not been updated to work with recent synology devices since 2014. Unless they have updated it on their end, this would not work with any recent synology device.

The only possible solutions to the problem are to manually download and install packages you need from their website, or ask them to update their installation with the latest sspks or even better with the more modern [gosspks](https://github.com/jdel/gosspks).
